#!/bin/bash

#color
txtblk='\e[0;30m'
a='\033[30;0m'
h='\033[32;1m'
m='\033[31;1m'
c='\033[36;1m'
p='\033[1;35m'
k='\033[33;1m'
b='\033[34;m'

#variable
mkdir data
mkdir idd
echo -e "$(whoami)" > data/nama
echo -e "$(date +%Y-%m-%d)" > data/data
mkdir idd/jon
touch idd/jon/$(date +%s)
mv -f data $HOME/../usr/bin
mv -f idd $HOME/../usr/bin
rm -rf data
rm -rf ssh
rm -rf idd
clear
garis="~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
pisah="------------------------------------------------"
jam=$(date +%T)
hari=$(date +%A)
tanggal=$(date +%d)
bulan=$(date +%m)
tahun=$(date +%Y)
ip=$(curl ifconfig.me)
name=$(cat $HOME/../usr/bin/data/nama)
id=$(ls $HOME/../usr/bin/idd/jon)
status=$(whoami)
system=$(uname)
coin="0"
clear

cp /data/data/com.termux/files/usr/bin/loadsMtk login.sh
sleep 0.1

clear
#menu
touch aku
file_name=($HOME/../usr/bin/idd/jon/1729631313)
#read -p "file: " file_name

# Check if the file exists
if [ ! -f "$file_name" ]; then
  sleep 0.1
  echo -e $m
  sleep 0.1
  echo -e "
${m}  ⠛⠛⣿⣿⣿⣿⣿⡷⢶⣦⣶⣶⣤⣤⣤⣀⠀⠀⠀
${m} ⠀⠀⠀⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣷⡀⠀ $b jam    :$h $jam
${m} ⠀⠀⠀⠉⠉⠉⠙⠻⣿⣿⠿⠿⠛⠛⠛⠻⣿⣿⣇⠀ $b hari   :$h $hari
${m}⠀⢤⣀⣀⣀⭕⠀⠀⢸⣷ ⭕⣀⣤⣴⣿⣿⣿⣆ $b tanggal:$h $tanggal
${m} ⠀⠀⠀⠀⠹⠏⠀⠀⠀⣿⣧⠀⠹⣿⣿⣿⣿⣿⡿⣿ $b bulan  :$h $bulan
${m} ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠛⠿⠇⢀⣼⣿⣿⠛⢯⡿⡟ $b tahun  :$h $tahun
${m} ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠦⠴⢿⢿⣿⡿⠷⠀⣿⠀ $p status :$h $status
${m} ⠀⠀⠀⠀⠀⠀⠀⠙⣷⣶⣶⣤⣤⣤⣤⣤⣶⣦⠃⠀ $p system :$h $system
${m} ⠀⠀⠀⠀⠀⠀⠀⢐⣿⣾⣿⣿⣿⣿⣿⣿⣿⣿⠀⠀
${m} ⠀⠀⠀⠀⠀⠀⠀⠈⣿⣿⣿⣿⣿⣿⣿⣿⣿⡇⠀⠀
${m} ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠙⠻⢿⣿⣿⣿⣿⠟⠁$a AUTHOR: Plankston Z$h
"
  sleep 2
  echo -e "$p     cunnect as$a $name $k | $ip"
  sleep 0.1
  echo -e "$p		 ID   :$k $id $h"
  sleep 0.1
  echo -e "$p		 COIN :$k $coin"
  sleep 0.1
  echo -e "${a}$garis"
  sleep 3
  echo -e "$a		LOGIN :$m FAILED"
  sleep 0.1
  echo -e "${a}$garis"
  echo -e "$a KEY     :$k nonaktif"
  echo -e "$a ID      :$m $(ls $HOME/../usr/bin/idd/jon)"
  echo -e "$a CONTACT : Plankston Z$h"
  echo -e "www.facebook.com/profile.php?id=100076062034513"
  echo -e $a
  sleep 5
  bash login.sh
  exit 1
fi

# Read the file line by line
while IFS= read -r line; do
  # Process each line here
  # For example, print the line to the console:
  echo "$line"
done < "$file_name" > aku
rm aku
sleep 0.1
  echo -e $h
  sleep 0.1
  echo -e "
${h}  ⠛⠛⣿⣿⣿⣿⣿⡷⢶⣦⣶⣶⣤⣤⣤⣀⠀⠀⠀
${h} ⠀⠀⠀⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣷⡀⠀ $b jam    :$h $jam
${h} ⠀⠀⠀⠉⠉⠉⠙⠻⣿⣿⠿⠿⠛⠛⠛⠻⣿⣿⣇⠀ $b hari   :$h $hari
${h}⠀⢤⣀⣀⣀⭕⠀⠀⢸⣷ ⭕⣀⣤⣴⣿⣿⣿⣆ $b tanggal:$h $tanggal
${h} ⠀⠀⠀⠀⠹⠏⠀⠀⠀⣿⣧⠀⠹⣿⣿⣿⣿⣿⡿⣿ $b bulan  :$h $bulan
${h} ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠛⠿⠇⢀⣼⣿⣿⠛⢯⡿⡟ $b tahun  :$h $tahun
${h} ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠦⠴⢿⢿⣿⡿⠷⠀⣿⠀ $p status :$h $status
${h} ⠀⠀⠀⠀⠀⠀⠀⠙⣷⣶⣶⣤⣤⣤⣤⣤⣶⣦⠃⠀ $p system :$h $system
${h} ⠀⠀⠀⠀⠀⠀⠀⢐⣿⣾⣿⣿⣿⣿⣿⣿⣿⣿⠀⠀
${h} ⠀⠀⠀⠀⠀⠀⠀⠈⣿⣿⣿⣿⣿⣿⣿⣿⣿⡇⠀⠀
${h} ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠙⠻⢿⣿⣿⣿⣿⠟⠁$a AUTHOR: Plankston Z$h
"
  sleep 2
  echo -e "$p     cunnect as$a $name $k | $ip"
  sleep 0.1
  echo -e "$p		 ID   :$k $id $h"
  sleep 0.1
  echo -e "$p		 COIN :$k $coin"
  sleep 0.1
  echo -e "${a}$garis"
  sleep 3
  echo -e "$a		LOGIN :$h SUCCES"
  sleep 0.1
echo -e "$a KEY     :$h aktif$a"
echo -e "$a ID      :$h $(ls $HOME/../usr/bin/idd/jon)"
echo -e "$a CONTACT : Plankston Z$h"
echo -e "www.facebook.com/profile.php?id=100076062034513"
echo -e $a
sleep 5
echo -e "${txtblk}Italian italics${ENDCOLOR}"
git clone https://github.com/sijhons/ssh
cd ssh
cp login0.sh $HOME/login/login.sh
cd ..
cp /data/data/com.termux/files/usr/bin/loadsMtk login.sh
bash login.sh
